services:
  dev:
    build: 
      dockerfile: Containerfile.dev
      context: .
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .dev.env